version: "3"

services:
  zoo1:
    image: zookeeper:3.4.10
    container_name: zoo1
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper:3.4.10
    container_name: zoo2
    restart: always
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper:3.4.10
    container_name: zoo3
    restart: always
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  hbase:
    image: harisekhon/hbase
    container_name: hbase
    restart: always
    ports:
      - 16000:16000
      - 16010:16010

  solr:
    image: solr:6.5-alpine
    container_name: solr
    restart: always
    ports:
     - 8983:8983
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore

  atlas:
    build: ./apache-atlas
    container_name: atlas
    restart: always
    ports:
      - 21000:21000

volumes:
  data:
